### ISSUE TITLE
commit_android_version_bump not working on Travis

### ISSUE THREAD

**Issue by ghost** [Jems22/fastlane-plugin-commit_android_version_bump#1]
Hi,

I installed `commit_android_version_bump` in my project and it works fine when I run locally on my Mac:

``` ruby
  def increment_build
    version_code = increment_version_code

    commit_android_version_bump(
      message: "[ci skip] Build bumped to #{version_code}"
    )

    branch = ENV["TRAVIS_BRANCH"] || "develop"
    push_to_git_remote(remote_branch: branch)
  end
```

But when I try to run on Travis, for some reason it doesn't work. It throws the error message "Could not find a build folder in the current repository's working directory".

Just FYI, my project follows a normal project structure with the app folder called `app`. Also, the command that I run before to increment the version code (`increment_version_code`) works fine, so I believe my project structure is not the issue here.

Can you help me please?

**Comment by Jems22** [comment]
Hello @vegidio-symbio 
Can you give me the complete log of your error to investigate more on your issue ?
Thanks

**Comment by vegidio** [comment]
Hey, I attached a .zip file with all the information that I have. There you will find:
1. `Fastfile` - the Fastlane configuration file of my project
2. `screenshot.png` - a screenshot of Travis when the error happens (notice that the plugin _increment_version_code_ that runs before, correctly finds my app build folder).
3. `Travis.txt` - has the full log output from Travis when the build failed.

The interesting thing about this issue is the fact that your plugin works fine when I run it locally on my Mac; it only fails on Travis.

I'm not sure what's the problem, but maybe it has something to do with how you look for the app build folder. Try to look at the source code for the other plugin that I'm using _increment_version_code_, since apparently the code that they are using there seems be finding the build folder without problems.

Anyway, thanks for the attention and for making this plugin. It's quite helpful.

[fastlane.zip](https://github.com/Jems22/fastlane-plugin-commit_android_version_bump/files/549044/fastlane.zip)

**Comment by vegidio** [comment]
Hello, do you have any feedback on this? Is there anything I can do to help?

**Comment by yapiskan** [comment]
@Jems22 I am also getting exact same error. seems like it can't locate the build folder to do the commit. same as @vegidio it is locally working on my mac, but travis runs the fastlane script on debian. that could be the reason.

let us know -- thanks.

**Comment by ghost** [comment]
This project looks abandoned. For those with the same problem, this is how I'm committing the changes on Travis:

`sh("git commit -am '[ci skip] Build bumped to #{build_number}'")`

Where `build_number` is the variable with the new build generated in the current CI job.

**Comment by Jems22** [comment]
Hi. 
I'm back on the project after a long delay (sorry for that)
I've updated the plugin adding a ```gradle_file_folder``` that let you specify the path to the folder containing your build.gradle file. instead of the app folder.
Hope this can help you with travis

**Comment by rahulraj64** [comment]
I also have the same issue when using bitbucket pipeline to build.
Error: "Could not find a build folder in the current repository's working directory."

Log
----

` fastlane beta
[10:35:28]: fastlane detected a Gemfile in the current directory
[10:35:28]: however it seems like you don't use `bundle exec`
[10:35:28]: to launch fastlane faster, please use
[10:35:28]: 
[10:35:28]: $ bundle exec fastlane beta
[10:35:28]: 
[10:35:28]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[10:35:28]: Installing Ruby gem 'fastlane-plugin-increment_version_code'...
[10:35:34]: Successfully installed 'fastlane-plugin-increment_version_code'
[10:35:35]: Installing Ruby gem 'fastlane-plugin-commit_android_version_bump'...
[10:35:41]: Successfully installed 'fastlane-plugin-commit_android_version_bump'
+---------------------------------------------+---------+-----------------------------+
|                                    Used plugins                                     |
+---------------------------------------------+---------+-----------------------------+
| Plugin                                      | Version | Action                      |
+---------------------------------------------+---------+-----------------------------+
| fastlane-plugin-increment_version_code      | 0.4.3   | increment_version_code      |
| fastlane-plugin-commit_android_version_bump | 0.2.0   | commit_android_version_bump |
+---------------------------------------------+---------+-----------------------------+
[10:35:41]: ------------------------------
[10:35:41]: --- Step: default_platform ---
[10:35:41]: ------------------------------
[10:35:41]: Driving the lane 'android beta' 🚀
[10:35:41]: ------------------------------------
[10:35:41]: --- Step: increment_version_code ---
[10:35:41]: ------------------------------------
[10:35:41]: The get_version_code plugin is looking inside your project folder (app)!
[10:35:41]:  -> Found a build.gradle file at path: (app/build.gradle)!
[10:35:41]:  -> line: (        versionCode 1
)!
[10:35:41]: ☝️ Version code has been changed to 2
[10:35:41]: -----------------------------------------
[10:35:41]: --- Step: commit_android_version_bump ---
[10:35:41]: -----------------------------------------
[10:35:41]: The commit_android_version_bump plugin is looking inside your project folder (app)!
+------------------+--------------+
|          Lane Context           |
+------------------+--------------+
| DEFAULT_PLATFORM | android      |
| PLATFORM_NAME    | android      |
| LANE_NAME        | android beta |
| VERSION_CODE     | 2            |
+------------------+--------------+
[10:35:41]: Could not find a build folder in the current repository's working directory.
+------+-----------------------------+-------------+
|                 fastlane summary                 |
+------+-----------------------------+-------------+
| Step | Action                      | Time (in s) |
+------+-----------------------------+-------------+
| 1    | default_platform            | 0           |
| 2    | increment_version_code      | 0           |
| 💥   | commit_android_version_bump | 0           |
+------+-----------------------------+-------------+
[10:35:41]: fastlane finished with errors
[!] Could not find a build folder in the current repository's working directory.
`

Can you please mention how to use the "gradle_file_folder" ?

bitbucket-pipelines.yml
--------------------------

image: bitriseio/docker-android

pipelines:
  default:
    - step:
        script:
              - fastlane beta

 Fastfile
--------

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    increment_version_code
    commit_android_version_bump
    push_to_git_remote
    gradle(task: "clean assembleRelease")
    changelog_from_git_commits(
        between: ["HEAD~2", "HEAD~1"]
    )
    end
end
